// new products
import NewProduct1_1 from "../../assets/NewProducts/product1_1.jpg";
import NewProduct1_2 from "../../assets/NewProducts/product1_2.jpg";
import NewProduct1_3 from "../../assets/NewProducts/product1_3.jpg";
import NewProduct2_1 from "../../assets/NewProducts/Product2_1.webp";
import NewProduct2_2 from "../../assets/NewProducts/Product2_2.webp";
import NewProduct2_3 from "../../assets/NewProducts/Product2_3.jpg";
import NewProduct3_1 from "../../assets/NewProducts/Product3_1.jpg";
import NewProduct3_2 from "../../assets/NewProducts/Product3_2.jpg";
import NewProduct3_3 from "../../assets/NewProducts/Product3_3.jpg";
import NewProduct4_1 from "../../assets/NewProducts/Product4_1.jpg";
import NewProduct4_2 from "../../assets/NewProducts/Product4_2.jpg";
import NewProduct4_3 from "../../assets/NewProducts/Product4_3.jpg";
import NewProduct5_1 from "../../assets/NewProducts/Product5_1.jpg";
import NewProduct5_2 from "../../assets/NewProducts/Product5_2.jpg";
import NewProduct5_3 from "../../assets/NewProducts/Product5_3.jpg";
import NewProduct6_1 from "../../assets/NewProducts/Product6_1.jpg";
import NewProduct6_2 from "../../assets/NewProducts/Product6_2.webp";
import NewProduct6_3 from "../../assets/NewProducts/Product6_3.jpg";
// special products
// and i'm also using both two products special and newproducts in for best selling and featured products category by merging them together
import SpecialProduct1_1 from "../../assets/SpecialProducts/Special1_1.jpg";
import SpecialProduct1_2 from "../../assets/SpecialProducts/Special1_2.jpg";
import SpecialProduct1_3 from "../../assets/SpecialProducts/Special1_3.jpg";
import SpecialProduct2_1 from "../../assets/SpecialProducts/Special2_1.jpg";
import SpecialProduct2_2 from "../../assets/SpecialProducts/Special2_2.jpg";
import SpecialProduct2_3 from "../../assets/SpecialProducts/Special2_3.jpg";
import SpecialProduct3_1 from "../../assets/SpecialProducts/Special3_1.webp";
import SpecialProduct3_2 from "../../assets/SpecialProducts/Special3_2.webp";
import SpecialProduct3_3 from "../../assets/SpecialProducts/Special3_3.webp";
import SpecialProduct4_1 from "../../assets/SpecialProducts/Special4_1.jpg";
import SpecialProduct4_2 from "../../assets/SpecialProducts/Special4_2.jpg";
import SpecialProduct4_3 from "../../assets/SpecialProducts/Special4_3.jpg";
import SpecialProduct5_1 from "../../assets/SpecialProducts/Special5_1.jpg";
import SpecialProduct5_2 from "../../assets/SpecialProducts/Special5_2.webp";
import SpecialProduct5_3 from "../../assets/SpecialProducts/Special5_3.webp";

// it isa main object with four arrays for products
const OurProductData = {
  NewProduct: [
    {
      id: 1,
      productName: "Fresh apple",
      weight: 5,
      price: 14,
      discount: 30,
      oldPrice: 18,
      availability: 2,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct1_1,
      image2: NewProduct1_2,
      image3: NewProduct1_3,
      type: "NewProduct",
      productType: "Fruit",
    },
    {
      id: 2,
      productName: "Sp. red fresh guava",
      weight: 4,
      price: 16,
      discount: 22,
      oldPrice: 18,
      availability: 7,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct2_1,
      image2: NewProduct2_2,
      image3: NewProduct2_3,
      type: "NewProduct",
      productType: "Fruit",
    },
    {
      id: 3,
      productName: "Fresh mussel (500g)",
      weight: 1,
      price: 11,
      discount: 30,
      oldPrice: 18,
      availability: 6,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct3_1,
      image2: NewProduct3_2,
      image3: NewProduct3_3,
      type: "NewProduct",
      productType: "Fruit",
    },
    {
      id: 4,
      productName: "Fresh seafoods",
      weight: 5,
      price: 15,
      discount: 27,
      oldPrice: 22,
      availability: 18,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct4_1,
      image2: NewProduct4_2,
      image3: NewProduct4_3,
      type: "NewProduct",
      productType: "Fruit",
    },
    {
      id: 5,
      productName: "Blackberry 100% organic",
      weight: 5,
      price: 17,
      discount: 26,
      oldPrice: 23,
      availability: 17,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct5_1,
      image2: NewProduct5_2,
      image3: NewProduct5_3,
      type: "NewProduct",
      productType: "Fruit",
    },
    {
      id: 6,
      productName: "Organic coconet",
      weight: 5,
      price: 11,
      discount: 30,
      oldPrice: 15,
      availability: 9,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct6_1,
      image2: NewProduct6_2,
      image3: NewProduct6_3,
      type: "NewProduct",
      productType: "Fruit",
    },
  ],
  SpecialProduct: [
    {
      id: 7,
      productName: "Fresh dryed almod (50g)",
      weight: 5,
      price: 16,
      discount: 40,
      oldPrice: 26,
      availability: 19,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "almond",
      image1: SpecialProduct1_1,
      image2: SpecialProduct1_2,
      image3: SpecialProduct1_3,
      type: "SpecialProduct",
      productType: "Fruit",
    },
    {
      id: 8,
      productName: "Vegetable tomato",
      weight: 5,
      price: 12,
      discount: 22,
      oldPrice: 16,
      availability: 8,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "tomato",
      image1: SpecialProduct2_1,
      image2: SpecialProduct2_2,
      image3: SpecialProduct2_3,
      type: "SpecialProduct",
      productType: "vegetable",
    },
    {
      id: 9,
      productName: "Fresh grassben",
      weight: 5,
      price: 11,
      discount: 40,
      oldPrice: 16,
      availability: 11,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "grassben",
      image1: SpecialProduct3_1,
      image2: SpecialProduct3_2,
      image3: SpecialProduct3_3,
      type: "SpecialProduct",
      productType: "vegetable",
    },
    {
      id: 10,
      productName: "Orange juice natural",
      weight: 2,
      price: 16,
      discount: 33,
      oldPrice: 22,
      availability: 6,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Orange",
      image1: SpecialProduct4_1,
      image2: SpecialProduct4_2,
      image3: SpecialProduct4_3,
      type: "SpecialProduct",
      productType: "Fruit",
    },
    {
      id: 11,
      productName: "Fruits banana 100% organic",
      weight: 3,
      price: 18,
      discount: 33,
      oldPrice: 24,
      availability: 12,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "banana",
      image1: SpecialProduct5_1,
      image2: SpecialProduct5_2,
      image3: SpecialProduct5_3,
      type: "SpecialProduct",
      productType: "Fruit",
    },
  ],
  BestSeller: [
    {
      id: 12,
      productName: "Fresh dryed almod (50g)",
      weight: 6,
      price: 19,
      discount: 29,
      oldPrice: 24,
      availability: 4,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "almond",
      image1: SpecialProduct1_1,
      image2: SpecialProduct1_2,
      image3: SpecialProduct1_3,
      type: "SpecialProduct",
      productType: "Fruit",
    },
    {
      id: 13,
      productName: "Vegetable tomato",
      weight: 4,
      price: 15,
      discount: 28,
      oldPrice: 19,
      availability: 3,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "tomato",
      image1: SpecialProduct2_1,
      image2: SpecialProduct2_2,
      image3: SpecialProduct2_3,
      type: "SpecialProduct",
      productType: "vegetable",
    },
    {
      id: 14,
      productName: "Fresh apple",
      weight: 4,
      price: 9,
      discount: 22,
      oldPrice: 12,
      availability: 4,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct1_1,
      image2: NewProduct1_2,
      image3: NewProduct1_3,
      type: "NewProduct",
      productType: "Fruit",
    },
    {
      id: 15,
      productName: "Sp. red fresh guava",
      weight: 8,
      price: 14,
      discount: 33,
      oldPrice: 18,
      availability: 4,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct2_1,
      image2: NewProduct2_2,
      image3: NewProduct2_3,
      type: "NewProduct",
      productType: "Fruit",
    },
    {
      id: 16,
      productName: "Blackberry 100% organic",
      weight: 7,
      price: 22,
      discount: 30,
      oldPrice: 28,
      availability: 8,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct5_1,
      image2: NewProduct5_2,
      image3: NewProduct5_3,
      type: "NewProduct",
      productType: "Fruit",
    },
    {
      id: 17,
      productName: "Organic coconet",
      weight: 8,
      price: 11,
      discount: 33,
      oldPrice: 19,
      availability: 9,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct6_1,
      image2: NewProduct6_2,
      image3: NewProduct6_3,
      type: "NewProduct",
      productType: "Fruit",
    },
  ],
  FeaturedProduct: [
    {
      id: 18,
      productName: "Sp. red fresh guava",
      weight: 7,
      price: 17,
      discount: 30,
      oldPrice: 22,
      availability: 11,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct2_3,
      image2: NewProduct2_2,
      image3: NewProduct2_1,
      type: "NewProduct",
      productType: "Fruit",
    },
    {
      id: 19,
      productName: "Fresh mussel (500g)",
      weight: 1,
      price: 18,
      discount: 30,
      oldPrice: 24,
      availability: 9,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct3_2,
      image2: NewProduct3_1,
      image3: NewProduct3_3,
      type: "NewProduct",
      productType: "Fruit",
    },
    {
      id: 20,
      productName: "Fresh grassben",
      weight: 6,
      price: 16,
      discount: 30,
      oldPrice: 23,
      availability: 6,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "grassben",
      image1: SpecialProduct3_2,
      image2: SpecialProduct3_1,
      image3: SpecialProduct3_3,
      type: "SpecialProduct",
      productType: "vegetable",
    },
    {
      id: 21,
      productName: "Orange juice natural",
      weight: 2,
      price: 27,
      discount: 30,
      oldPrice: 33,
      availability: 4,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Orange",
      image1: SpecialProduct4_3,
      image2: SpecialProduct4_2,
      image3: SpecialProduct4_1,
      type: "SpecialProduct",
      productType: "Fruit",
    },
    {
      id: 22,
      productName: "Vegetable tomato",
      weight: 3,
      price: 10,
      discount: 30,
      oldPrice: 14,
      availability: 9,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "tomato",
      image1: SpecialProduct2_1,
      image2: SpecialProduct2_3,
      image3: SpecialProduct2_2,
      type: "SpecialProduct",
      productType: "vegetable",
    },
    {
      id: 23,
      productName: "Fresh apple",
      weight: 8,
      price: 11,
      discount: 30,
      oldPrice: 15,
      availability: 1,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct1_3,
      image2: NewProduct1_2,
      image3: NewProduct1_1,
      type: "NewProduct",
      productType: "Fruit",
    },
    {
      id: 24,
      productName: "Sp. red fresh guava",
      weight: 3,
      price: 16,
      discount: 12,
      oldPrice: 18,
      availability: 12,
      size: 2,
      secondSize: 3,
      sku: 12345,
      tag: "Apple",
      image1: NewProduct2_2,
      image2: NewProduct2_1,
      image3: NewProduct2_3,
      type: "NewProduct",
      productType: "Fruit",
    },
  ],
};
export default OurProductData;
